version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_app
    depends_on:
      - db
    env_file: .env
    ports:
      - "8080:8080"
    restart: unless-stopped

  db:
    image: postgres:alpine
    container_name: postgres
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  db_data: